---
- hosts: all
  strategy: free
  gather_facts: False

  tasks:
  - name: install python
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
    changed_when: false

- hosts: dockerhosts
  strategy: free

  tasks:
  - name: Only run "update_cache=yes" if the last one is more than 3600 seconds ago
    apt: update_cache=yes cache_valid_time=3600

  - name: Upgrade all packages to the latest version
    apt:
      name: "*"
      state: latest
      force_apt_get: yes

  - name: Install a list of packages
    apt:
      name: "{{ packages }}"
      state: latest
      force_apt_get: yes
    vars:
      packages:
      - software-properties-common
      - apt-transport-https
      - curl
      - ca-certificates
      - gnupg-agent
      - software-properties-common

  - name: Add Docker GPG key
    apt_key: url=https://download.docker.com/linux/ubuntu/gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb [arch=amd64] https://download.docker.com/linux/{{ansible_distribution|lower}} {{ansible_distribution_release}} stable

  - name: Install Docker
    apt:
      name: docker-ce
      update_cache: yes
      force_apt_get: yes

  - name: Add K8S GPG key
    apt_key: url=https://packages.cloud.google.com/apt/doc/apt-key.gpg

  - name: Add Docker APT repository
    apt_repository:
      repo: deb https://apt.kubernetes.io/ kubernetes-xenial main

  - name: Install K8S
    apt:
      name: "{{ packages }}"
      update_cache: yes
      force_apt_get: yes
    vars:
      packages:
        - kubelet
        - kubeadm
        - kubectl


- hosts: kmaster
  strategy: free

  tasks:
#  - name: make config dir
#    raw: mkdir -p $HOME/.kube
#    changed_when: false

#  - name: copy config to config dir
#    raw: cp -i /etc/kubernetes/admin.conf $HOME/.kube/config
#    changed_when: false

#  - name: chown config
#    raw: chown $(id -u):$(id -g) $HOME/.kube/config
#    changed_when: false

  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes

  - name: Copy network cfg
    copy:
      src: files/kube-flannel.yml
      dest: /tmp/kube-flannel.yml

  - name: install Pod network
    shell: kubectl apply -f /tmp/kube-flannel.yml >> ~/pod_network_setup.txt

- hosts: kslaves
  strategy: free

  tasks:
  - name: Remove dependencies that are no longer required
    apt:
      autoremove: yes



